### ISSUE TITLE
It doesn't work with NextJS and local/session Storage

### ISSUE THREAD

**Issue by IsaacMujica** [Oblosys/react-hook-tracer#2]
It doesn't work when you are using NextJS and try to access to local/session Storage through a custom hook.
The messages is:
```
Server Error
ReferenceError: sessionStorage is not defined
```

An example of the custom hook is the following:

```
const useAccountInitialState = () => {
  const [state, setState] = useState({
    account: {
      details: {}
    },
    accountStorage: () => ({})
  })
  const accountStorage: AccountStorage = useCallback((time = STORAGE_EXPIRE_DAYS) => ({
    details: JSON.stringify(localStorage.get('details'))
  }), [])

  const account: () => AccountInitialState = useCallback(() => ({
    details: accountStorage().details ?? {details: {}}
  }), [])

  useEffect(() => {
    setState({account, accountStorage})
  }, [])
  
  return state
}
```

### I'm using:

- NextJS v13.2.4
- React v18.2.0

**Comment by Oblosys** [comment]
Thanks for creating the issue. Server-side rendering isn't supported yet, but it might be relatively straightforward to implement by disabling tracing on the server. It would trigger a render-mismatch console warning for each trace panel, but apart from that it should work. I'll take a look at it when I have some free time.

**Comment by IsaacMujica** [comment]
Any time, if you need extra evidence or details, please just let me know.

Regards!
